import BlogPost from "../models/BlogPost.js";

const initialBlogPosts = [
  new BlogPost(
    0,
    "Lorem Ipsum Dolor Sit Amet",
    new Date(),
    "Reilly Carver",
    `Cras eget fringilla nisi. Quisque pharetra leo id dolor mollis, eu malesuada tellus fermentum. Donec vel dolor et metus cursus auctor eget vel felis. Integer aliquet mi mollis arcu mollis, a luctus velit iaculis. Ut eget ultricies nulla, in vehicula arcu. Etiam eget turpis vitae lacus pellentesque vulputate. Mauris posuere erat eu velit sagittis imperdiet. Vivamus ultrices ex justo. Quisque in interdum neque.\n\n` +
      `Etiam eleifend ex nec neque posuere interdum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris facilisis leo elementum, aliquet lectus quis, dictum orci. Duis euismod mollis massa volutpat tincidunt. Donec molestie tincidunt sem et luctus. Proin eu est nunc. Sed facilisis augue et aliquet eleifend. Vestibulum elementum est nec ante eleifend egestas. Duis eget accumsan lectus. Vestibulum vel pharetra justo. Cras congue consequat vestibulum. Etiam molestie fringilla porta. Vivamus interdum vulputate leo. Phasellus sollicitudin tincidunt hendrerit.\n\n` +
      `Donec et euismod elit. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque magna magna, tempor id tincidunt nec, elementum nec eros. Integer fringilla, justo et scelerisque iaculis, lectus tellus rutrum leo, sit amet viverra arcu felis et tortor. Proin vitae velit rhoncus, volutpat ligula non, elementum magna. Sed blandit faucibus maximus. Aliquam facilisis tristique erat, quis placerat libero sollicitudin nec. Sed eget quam ac nunc accumsan venenatis at a nisi. Quisque nec luctus mi, eget dictum justo. Nam eleifend erat ut tempor interdum. Morbi dictum placerat leo non ornare. Praesent vel felis et ante varius egestas. Sed ultrices mattis sapien, ut condimentum diam hendrerit in.\n\n` +
      `Maecenas eu facilisis lacus, ut tristique nisi. Sed rutrum tellus ex, eu consequat sem accumsan eget. Nam in aliquam odio, ac laoreet elit. Cras pellentesque dui sed posuere interdum. Morbi et mauris eu elit ullamcorper consequat dictum a diam. Vestibulum porta pellentesque libero a semper. Cras venenatis, leo sed convallis egestas, diam mauris lobortis lacus, eu faucibus dui enim mollis urna. Maecenas eu libero laoreet urna vulputate consequat. Maecenas quis odio laoreet, pulvinar massa id, consequat justo. Aenean lacinia iaculis metus, in pretium dui tempor ac. Morbi pretium risus ac massa facilisis, sed vehicula ex aliquet. Fusce volutpat blandit tristique.\n\n` +
      `Duis maximus mi eu lacinia convallis. Phasellus at tempor turpis. Pellentesque sed sem fermentum, rhoncus nibh et, sagittis est. Praesent sed egestas ex. Nam vitae ante eu orci pharetra semper non eget odio. Integer venenatis ex mi, eget sollicitudin lectus tincidunt vitae. Curabitur non dolor massa. Vestibulum vel semper ex. Ut malesuada convallis sapien, non vulputate dui dapibus a. Donec sed iaculis turpis. Curabitur dictum tortor in quam placerat, quis tincidunt lorem semper. Quisque ullamcorper justo sed tincidunt semper. Cras at hendrerit enim, sit amet mattis justo. Donec faucibus nibh vel magna finibus hendrerit. Proin sit amet semper purus. Nulla sem dolor, commodo quis ornare eu, eleifend non tortor.`
  ),
  new BlogPost(
    1,
    "Interdum Et Malesuada Fames Ac",
    new Date(),
    "Delicia Noel",
    `Etiam felis purus, ultrices vel metus quis, molestie malesuada nisl. Aenean id convallis ipsum. Cras eros lacus, rutrum scelerisque aliquam ut, ornare quis erat. Ut tempor sagittis viverra. In sem orci, porta ut tempor vel, euismod id ex. Nunc cursus sit amet ante at ultricies. Nullam eu enim in enim ullamcorper semper vitae eget felis. Integer blandit augue eu ligula dignissim, laoreet fermentum magna tristique. In pharetra elementum mi vel blandit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sit amet varius elit, at iaculis nunc. Suspendisse pretium egestas dui, eget ultricies velit euismod non. Praesent dictum turpis id malesuada luctus. Aliquam aliquet ac augue id varius.\n\n` +
      `Sed non tincidunt nisi. Nulla facilisi. Nam et nunc eget risus tincidunt bibendum. Etiam sit amet scelerisque tortor. Proin consequat congue augue ut rutrum. Etiam non pulvinar est, vitae fringilla dui. Nulla vel elit et tellus venenatis tempus. Nunc varius in urna sit amet ultricies. Proin sollicitudin porttitor diam, vel vehicula orci volutpat non. Sed vitae arcu porta, faucibus velit et, interdum purus. Curabitur mattis, mauris mattis blandit auctor, mauris sem suscipit odio, ut mollis libero elit sed sapien. Donec convallis turpis in nibh malesuada bibendum. Quisque at tempus felis.\n\n` +
      `Donec maximus, risus id interdum dapibus, dui lacus ultrices turpis, sed ultrices arcu erat id arcu. Nam varius libero ut risus accumsan luctus. Nullam viverra et mi ut consequat. Sed ultrices porta mi eu sodales. Fusce ac libero et velit interdum semper suscipit et erat. Cras cursus, massa a eleifend cursus, lacus tellus maximus diam, at molestie felis lorem ut ante. Curabitur sit amet lectus eu sem tempor egestas et sed enim. Sed dui ex, rutrum non magna quis, blandit dapibus mi. Sed mattis pellentesque est, vitae blandit est rhoncus id. Pellentesque sit amet rhoncus mi, vel eleifend augue. Nam faucibus, ante vel rhoncus finibus, elit ligula scelerisque nisi, a cursus quam ipsum at quam. Mauris sed tincidunt urna. Sed feugiat, magna id iaculis tempor, lectus ipsum efficitur ex, imperdiet aliquam tellus turpis at nunc. Integer ornare tortor odio, scelerisque facilisis orci molestie sed. Aenean tempor orci eget lorem ultrices, semper vulputate ligula tincidunt. Suspendisse lectus enim, tempor sit amet dolor at, mattis eleifend risus.\n\n` +
      `Aliquam erat volutpat. Pellentesque ultricies justo sit amet massa condimentum volutpat. Mauris efficitur sollicitudin tempor. Suspendisse aliquam felis purus, rhoncus vehicula odio vulputate sed. Donec eget pretium nisl, sed malesuada metus. Etiam tempor lacus nisl, nec efficitur elit euismod ac. In euismod orci bibendum ligula aliquam faucibus. Maecenas vehicula dictum sem a pulvinar. Cras facilisis nisi ac laoreet commodo. Proin ullamcorper purus vel diam porta egestas at vel arcu.\n\n` +
      `Mauris pellentesque elit non suscipit aliquet. Nullam interdum magna dolor, sit amet congue nibh consectetur auctor. Ut vehicula lorem quis laoreet semper. Phasellus rhoncus condimentum massa, nec egestas arcu vulputate et. Donec non sem consequat, bibendum erat quis, aliquam mi. Praesent a ex nec tellus pharetra commodo. Duis ullamcorper magna diam, eu euismod enim dapibus id. Nam tempus auctor vulputate. Curabitur mollis, arcu sed finibus fringilla, urna ligula tincidunt sapien, vitae feugiat mauris urna ut lorem. Curabitur sed pretium turpis. Phasellus auctor metus vel hendrerit accumsan. Quisque ornare sagittis lectus nec pellentesque. Vivamus tincidunt sapien egestas malesuada iaculis. Donec porttitor tellus metus, malesuada accumsan eros maximus sit amet.\n\n`
  ),
  new BlogPost(
    2,
    "Pellentesque Elit Ante, Commodo Ut",
    new Date(),
    "Nadia Capri",
    `Vivamus enim lacus, scelerisque id fermentum eget, tincidunt quis metus. Ut a turpis dui. Duis volutpat nibh et condimentum pharetra. Vestibulum posuere, quam et porta ultrices, purus enim volutpat nulla, a ultricies lorem urna non sem. Nullam et luctus ante, nec rhoncus odio. Nulla tempus egestas scelerisque. Pellentesque semper scelerisque dictum. Vestibulum condimentum tellus ac tellus scelerisque, sed iaculis felis efficitur. Nunc suscipit nisi vitae orci luctus, ut facilisis massa molestie. Nullam at semper velit, eget elementum augue. Vestibulum pharetra lectus eu odio euismod sagittis. Ut id lacus eget tortor malesuada ullamcorper.\n\n` +
      `Nam sed turpis dapibus, ullamcorper tortor id, tempus lectus. Vivamus cursus at odio ac finibus. Etiam auctor ex at lacus viverra, in aliquet velit venenatis. Etiam rhoncus nunc magna, in imperdiet lacus laoreet eget. Vestibulum bibendum ante ut nunc efficitur interdum. Pellentesque bibendum tellus mauris, id facilisis dolor suscipit non. Vivamus sed ex vel metus rhoncus luctus ut id magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et eros nulla. Integer convallis sapien mauris, in fringilla arcu tempus lobortis.\n\n` +
      `Aenean non neque at libero consequat laoreet sit amet vitae elit. Etiam aliquet tincidunt lacus, vel ultrices nulla tincidunt ac. Donec efficitur aliquet tristique. Phasellus id vulputate turpis. Cras imperdiet diam at vestibulum egestas. In consequat faucibus cursus. Pellentesque quam tortor, dignissim nec quam eu, consectetur pretium purus. Fusce ac est ac libero condimentum ullamcorper. Phasellus ut pretium leo. Mauris non nunc sapien. Vivamus sit amet efficitur leo. Duis malesuada mi eget erat ornare aliquam. Sed faucibus purus ut ligula dapibus, a pulvinar tellus sollicitudin. Proin orci neque, pretium non sollicitudin sit amet, hendrerit elementum quam.\n\n` +
      `In pellentesque bibendum leo, nec pharetra felis euismod quis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis lobortis, orci sed venenatis convallis, nibh mauris gravida velit, a varius nulla magna vitae velit. Curabitur ut turpis odio. Donec fermentum eu mauris eget fringilla. Quisque vulputate posuere sagittis. Suspendisse ut tincidunt ante. Morbi erat ante, semper ac felis eu, tempus blandit ligula. Mauris facilisis massa est, et rhoncus felis ornare ac.\n\n` +
      `Morbi suscipit vitae massa sed consequat. Etiam vehicula orci id sapien iaculis placerat. Praesent in quam eu massa mollis scelerisque. Mauris et ultricies ipsum. Suspendisse sagittis congue orci ut faucibus. Nam sit amet neque placerat, lacinia dolor nec, facilisis arcu. Etiam laoreet euismod velit vel dignissim. Nam sit amet euismod neque, sit amet interdum nunc.\n\n`
  ),
];

export default initialBlogPosts;
